// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_ceo: dynamic(() => import("./AboutCeo")),
  call_to_action: dynamic(() => import("./CallToAction")),
  countries: dynamic(() => import("./Countries")),
  faqs: dynamic(() => import("./Faqs")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  quote: dynamic(() => import("./Quote")),
  reviews: dynamic(() => import("./Reviews")),
  services: dynamic(() => import("./Services")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  video_reviews: dynamic(() => import("./VideoReviews")),
  why_us: dynamic(() => import("./WhyUs")),
};
